name: Keep Streamlit App Alive

on:
  schedule:
    - cron: "*/10 * * * *"   # Runs every 10 minutes
  workflow_dispatch:          # Allow manual trigger too

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Streamlit App
        run: |
          curl -s https://portfolioapp-xr8izn8vwoan9an9wguefp.streamlit.app/ > /dev/null
