name: Keep Streamlit App Alive

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Streamlit app
        run: curl -s https://portfolioapp-xr8izn8vwoan9an9wguefp.streamlit.app/ > /dev/null
